IDOWN/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'api/', include('api.urls',namespace='api')),
    path('',views.dashboard,name='dashboard'),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('assets/',include('assets.urls',namespace="assets")),
    path('webssh/',include('webssh.urls',namespace='webssh')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 全局403
handler403 = 'IDOWN.views.page_forbidden'

# 全局404
handler404 = 'IDOWN.views.page_not_found'

# 全局500
handler500 = 'IDOWN.views.page_error'

apps/webssh/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2019-07-14 20:28
# @Author  : kbsonlong
# @Email   : kbsonlong@gmail.com
# @Blog    : www.alongparty.cn
# @File    : urls.py
# @Software: PyCharm
from django.urls import path,re_path
from . import views

app_name = 'webssh'
urlpatterns = [
    path('', views.index,name='index'),
    path('web_ssh/<int:pk>/', views.get_info,name='web_ssh'),
    path('upload_ssh_key/', views.upload_ssh_key,name='upload_ssh_key'),
    path('login_record/', views.login_fort_record,name='login_record'),
    re_path(r'record_play/(?P<pk>[0-9]+)/', views.record_play, name='record_play'),
    re_path(r'ssh/(?P<pk>[0-9]+)/', views.ssh_terminal, name='ssh_terminal'),
]

apps/webssh/models.py
from django.db import models
from cryptography.fernet import Fernet
from django.contrib.auth import get_user_model

# Create your models here.


User = get_user_model()

class SshUser(models.Model):
    """
    WebSSH登录信息
    """
    username = models.OneToOneField(User, verbose_name='用户', on_delete=models.CASCADE)
    password = models.CharField(max_length=200,verbose_name="密码",help_text="存放登录密码或者秘钥密码")
    ssh_key = models.TextField(verbose_name="秘钥信息",null=True,blank=True,editable=False)
    is_key = models.BooleanField(default=True, verbose_name="是否使用秘钥登录", help_text="默认以秘钥登录")

    class Meta:
        verbose_name = "WebSSH登录信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class FortRecord(models.Model):
    """
    操作记录表
    """
    record_modes = (
        ('ssh', 'ssh'),
        ('guacamole', 'guacamole')
    )

    login_user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    fort = models.CharField(max_length=32, verbose_name='登录主机及用户')
    remote_ip = models.GenericIPAddressField(verbose_name='远程地址')
    start_time = models.CharField(max_length=64, verbose_name='开始时间')
    login_status_time = models.CharField(max_length=16, verbose_name='登录时长')
    record_file = models.CharField(max_length=256, verbose_name='操作记录')
    record_mode = models.CharField(max_length=10, choices=record_modes, verbose_name='登录协议', default='ssh')

    class Meta:
        db_table = 'ops_fort_record'
        verbose_name = '操作记录表'
        verbose_name_plural = '操作记录表'

apps/webssh/views.py
import os
import json
import datetime
# Create your views here.
from django.shortcuts import render, HttpResponse,HttpResponseRedirect
from django.conf import settings
from django.contrib.auth.decorators import login_required,permission_required
from django.http import JsonResponse, FileResponse
from django.contrib.auth import get_user_model


from .models import SshUser,FortRecord
from assets.models import Asset
from .channel.websftp import SFTP


User = get_user_model()

@login_required
def index(request):
    user = SshUser.objects.filter(username=request.user)

    return render(request, 'index.html')

def get_info(request,pk):
    asset = Asset.objects.filter(pk=pk)
    user = SshUser.objects.get(username=request.user)

    ret = {}
    try:
        if user:
            ip = asset[0].server.i_ip
            if ip:
                ip= ip
            else:
                ip = asset[0].server.local_ip
            username = user.username
            password = user.password
            ssh_key = user.ssh_key
            if user.is_key:
                auth = 'key'
            else:
                auth = ''
            ret = {"username": username, 'password': password, 'ssh_key': ssh_key, 'auth': auth, 'ip': ip, 'port': 22,
                   "static": True}
        else:
            return HttpResponseRedirect('/webssh/',locals())
    except Exception as e:
        ret['status'] = False
        ret['error'] = '请求错误,{}'.format(e)
    finally:

        return HttpResponse(json.dumps(ret))

def upload_ssh_key(request):
    if request.method == 'POST':

        username = request.POST.get('user')
        password = request.POST.get('password')
        pkey = request.FILES.get('pkey')
        auth = request.POST.get('auth')
        user = User.objects.filter(username=username).first()

        if user :
            sshuser = SshUser.objects.filter(username_id=user.id).first()
            if auth == 'pwd' and password:
                data = {'username_id':user.id,'password':password,'is_key':False}
            elif pkey:
                ssh_key = pkey.read().decode('utf-8')
                data = {'username_id':user.id,'password':password,'ssh_key':ssh_key}
            else:
                return HttpResponse(json.dumps({'status':False,'message':'密码或秘钥文件不能为空'}))
            if not sshuser:
                SshUser.objects.create(**data)
                message = '{} 认证信息保存成功'.format(username)
                status = True
            else:
                message = '{} 认证信息已存在'.format(username)
                status = False
        else:
            status = False
            message = '用户名【{}】不存在，请联系管理员'.format(username)

        return HttpResponse(json.dumps({'status':status,'message':message}))


@login_required
def ssh_terminal(request, pk):
    server_obj = Asset.objects.get(pk=pk)
    ssh_server_ip = server_obj.server.i_ip
    group_name = server_obj.business_unit.name
    username = request.user.username


    if request.method == 'GET':
        download_file = request.GET.get('download_file')

        if download_file:
            download_file_path = os.path.join(settings.MEDIA_ROOT, 'admin_files', username, 'download',
                                              ssh_server_ip)
            sftp = SFTP(ssh_server_ip, request.user.id)
            response = sftp.download_file(download_file, download_file_path)
            return response
        else:
            remote_ip = request.META.get('REMOTE_ADDR')
            return render(request, 'terminal.html', locals())
    elif request.method == 'POST':
        try:
            upload_file = request.FILES.get('upload_file')
            upload_file_path = os.path.join(settings.MEDIA_ROOT, 'fort_files', username, 'upload',
                                            ssh_server_ip)
            # sftp = SFTP(ssh_server_ip, server_obj.port, server_obj.username,
            #             CryptPwd().decrypt_pwd(server_obj.password))
            sftp = SFTP(ssh_server_ip, request.user.id)
            status,message = sftp.upload_file(upload_file, upload_file_path)

            if status:
                code = 200
            else:
                code = 500
            return JsonResponse({'code': code, 'msg': message})
        except Exception as e:
            return JsonResponse({'code': 500, 'msg': '上传失败！{}'.format(e)})


@login_required
def login_fort_record(request):
    if request.method == 'GET':
        user = request.user
        if user.is_superuser:
            results = FortRecord.objects.select_related('login_user').all()
        else:
            results = FortRecord.objects.select_related('login_user').filter(id=user.id)
        return render(request, 'login_admin_record.html', locals())
    elif request.method == 'POST':
        start_time = request.POST.get('startTime')
        end_time = request.POST.get('endTime')
        new_end_time = datetime.datetime.strptime(end_time, '%Y-%m-%d') + datetime.timedelta(1)
        end_time = new_end_time.strftime('%Y-%m-%d')
        try:
            records = []
            search_records = FortRecord.objects.select_related('login_user').filter(start_time__gt=start_time,
                                                                                    start_time__lt=end_time)
            for search_record in search_records:
                record = {
                    'id': search_record.id,
                    'login_user': search_record.login_user.username,
                    'fort': search_record.fort,
                    'record_mode': search_record.get_record_mode_display(),
                    'remote_ip': search_record.remote_ip,
                    'start_time': search_record.start_time,
                    'login_status_time': search_record.login_status_time
                }
                records.append(record)
            return JsonResponse({'code': 200, 'records': records})
        except Exception as e:
            return JsonResponse({'code': 500, 'error': '查询失败：{}'.format(e)})


@login_required
def record_play(request, pk):
    record = FortRecord.objects.select_related('login_user').get(id=pk)
    MEDIA_URL = settings.MEDIA_URL
    if record.record_mode == 'ssh':
        return render(request, 'ssh_record_play.html', locals())
    else:
        return render(request, 'guacamole_record_play.html', locals())

apps/webssh/templates/guacamole_play.html
{% load staticfiles %}
<!DOCTYPE HTML>
<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
-->
<html>

    <head>
        <title>{{ record.admin_server }}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" type="text/css" href="{% static 'guacamole/css/playback.css' %}">
    </head>

    <body>

        <!-- Guacamole recording player -->
        <div class="player" style="width: 100%">

            <!-- Player display -->
            <div id="display"></div>

            <!-- Player controls -->
            <div class="controls">
                <button id="play-pause">Play</button>
                <label for="position-slider"></label><input id="position-slider" type="range">
                <span id="position">00:00</span>
                <span>/</span>
                <span id="duration">00:00</span>
            </div>

        </div>

        <!-- Guacamole JavaScript API -->
        <script type="text/javascript" src="{% static 'guacamole/js/all.min.js' %}"></script>
        <!-- -->
        <script type="text/javascript" src="{% static 'guacamole/js/playback.js' %}"></script>

        <script type="text/javascript">
            initExamplePlayer('{{ MEDIA_URL }}{{ record.admin_record_file }}')
        </script>
    </body>

</html>

apps/webssh/templates/index.html
{% extends 'base.html' %}
{% block title %} 用户SSH认证信息{% endblock %}
{% block ext_css %}
    <link rel="icon" href="/static/favicon.ico"/>
    <link rel="stylesheet" href="/static/xterm/xterm.css"/>
    <!--<link href="https://cdn.bootcss.com/xterm/3.14.5/xterm.css" rel="stylesheet">-->
    <link rel="stylesheet" href="/static/xterm/style.css"/>
    <link rel="stylesheet" href="/static/bootstrap.min.css"/>
    <!--<link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">-->
    <style>
        .input-width {
            width: 20%;
            display: inline-block;
        }

        .hide {
            display: none;
        }
    </style>
{% endblock %}
{% block content %}

<div style="margin-top: 10px" id="form">
    <form class="form-horizontal">
        {% csrf_token %}
{#        <div class="form-group">#}
{#            <label class="col-sm-2 control-label">主机地址</label>#}
{#            <div class="col-sm-10">#}
{#                <input type="text" class="input-width form-control" id="host" placeholder="host">#}
{#            </div>#}
{#        </div>#}
{##}
{#        <div class="form-group">#}
{#            <label class="col-sm-2 control-label">端口</label>#}
{#            <div class="col-sm-10">#}
{#                <input type="text" class="input-width form-control" id="port" value="22">#}
{#            </div>#}
{#        </div>#}

        <div class="form-group">
            <label class="col-sm-2 control-label">用户名</label>
            <div class="col-sm-10">
                <input type="text" class="input-width form-control" id="user" name="username" placeholder="user">
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">认证类型</label>
            <div class="col-sm-10">
                <label class="radio-inline">
                    <input type="radio" name="auth" id="inlineRadio1" value="pwd" checked> 密码认证
                </label>
                <label class="radio-inline">
                    <input type="radio" name="auth" id="inlineRadio2" value="key"> 秘钥认证
                </label>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">密码</label>
            <div class="col-sm-10">
                <input type="password" name="password" class="input-width form-control" id="password" placeholder="password">
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">秘钥文件</label>
            <div class="col-sm-10">
                <input type="file" id="pkey">
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <span id="helpBlock" class="help-block">
                   注意:
                    <p style="color: red">1、当认证类型为密码认证时, 秘钥输入框的内容将被忽略</p>
                    <p style="color: red">2、当认证类型为秘钥认证时, 如果密码输入框不为空, 则密码输入框的内容将作为秘钥的解密密码</p>
                </span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="button" class="btn btn-default" onclick="get_connect_info()">提&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;交
                </button>
            </div>
        </div>
    </form>
</div>

<div id="webssh-terminal" class="hide">
    <div id="terminal"></div>
</div>

{% endblock %}
<!--<script src="/static/jquery.min.js"></script>-->
{#<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>#}
<!--<script src="/static/xterm/xterm.js"></script>-->
{% block script %}
    <script src="https://cdn.bootcss.com/xterm/3.14.5/xterm.min.js"></script>
    <script src="/static/webssh.js"></script>
{% endblock %}

apps/webssh/templates/login_admin_record.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} 用户操作记录 {% endblock %}
{% block head %}
    <link rel="stylesheet"
          href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'adminlet-2.4.10/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <style>
        /* dataTables列内容居中 */
        #example1 > tbody > tr > td {
            text-align: center;
        }

        /* dataTables表头居中 */
        #example1 > thead:first-child > tr:first-child > th {
            text-align: center;
        }
    </style>
    <link rel="stylesheet" href="{% static 'plugins/jquery-confirm/dist/jquery-confirm.min.css' %}">
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <br>
            <div class="col-sm-2">
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" id="loginLogStartTime" class="form-control pull-right"
                               data-date-format="yyyy-mm-dd" placeholder="开始时间">
                        <span class="input-group-addon">
										                    <span class="glyphicon glyphicon-calendar"></span>
										                </span>
                    </div>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" id="loginLogEndTime" class="form-control pull-right"
                               data-date-format="yyyy-mm-dd" placeholder="结束时间">
                        <span class="input-group-addon" onclick="searchUserLog()">
										                    <span class="glyphicon glyphicon-search"
                                                                  style="cursor: pointer"></span></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <!-- /.box -->
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>用户</th>
                            <th>登录主机</th>
                            <th>连接方式</th>
                            <th>远程地址</th>
                            <th>开始时间</th>
                            <th>登录时长</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for result in results %}

                            <tr>
                                <td>{{ result.login_user.username }}</td>
                                <td>{{ result.fort }}</td>
                                <td>
                                    {% if result.record_mode == 'ssh' %}
                                        <small class="label label-primary"> ssh</small>
                                    {% else %}
                                        <small class="label label-info"> guacamole</small>
                                    {% endif %}
                                </td>
                                <td>{{ result.remote_ip }}</td>
                                <td>{{ result.start_time }}</td>
                                <td>{{ result.login_status_time }}</td>
                                <td>
                                    {% if result.record_mode == 'ssh' %}
                                        <a onclick="window.open('{% url 'webssh:record_play' result.id %}','newwindow', 'height=500, width=1005, top=200, left=200, toolbar=no, menubar=no, scrollbars=no, location=no, status=no')"
                                           class="btn btn-xs btn-warning btn-replay">回放</a>
                                    {% else %}
                                        <a onclick="window.open('{% url 'webssh:record_play' result.id %}','newwindow')"
                                           class="btn btn-xs btn-warning btn-replay">回放</a>
                                    {% endif %}
                                </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
    <!-- /.row -->

{% endblock %}


{% block addscript %}
    <!-- DataTables -->
    <script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <!-- bootstrap datepicker -->
    <script src="{% static 'adminlet-2.4.10/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>

    <script src="{% static 'plugins/jquery-confirm/dist/jquery-confirm.min.js' %}"></script>
    <script>
        $(function () {
            table = $('#example1').DataTable({
                columnDefs: [{
                    'targets': [-1],
                    'orderable': false
                }],
                "order": [[4, "desc"]]
            });

            //Date picker
            $('#loginLogStartTime, #loginLogEndTime').datepicker({
                autoclose: true
            });
        });

        // 按日期搜索
        function searchUserLog() {
            let startTime = $('#loginLogStartTime').val();
            let endTime = $('#loginLogEndTime').val();
            var csrf = $("[name='csrfmiddlewaretoken']").val();
            if (startTime.length === 0 || endTime.length === 0) {
                $.alert({
                    title: 'Tips',
                    type: 'red',
                    content: '请选择起始时间！'
                });
                return false;
            }
            $.ajax({
                dataType: "JSON",
                url: '{% url 'webssh:login_record' %}',
                type: "POST",  //提交类似
                data: {
                    "startTime": startTime,
                    "endTime": endTime,
                },
                success: function (response) {
                    if (response.records.length === 0) {
                        $.alert({
                            title: 'Tips',
                            type: 'red',
                            content: '该时间段内没有任何操作！'
                        });
                    } else {
                        $.alert({
                            title: 'Tips',
                            type: 'green',
                            content: '查询完成！'
                        });
                        table.clear().draw();
                        for (let i = 0; i < response.records.length; i++) {
                            let result = response.records[i];
                            let admin_record_mode = result['admin_record_mode'] === 'ssh' ? '<small class="label label-primary"> ssh</small>' : '<small class="label label-info"> guacamole</small>';
                            table.row.add([
                                result['admin_login_user'],
                                result['admin_server'],
                                admin_record_mode,
                                result['admin_remote_ip'],
                                result['admin_start_time'],
                                result['admin_login_status_time'],
                                '<a onclick="window.open(\'/assets/admin_play/' + result['id'] + '/' + '\',\'newwindow\', \'height=500, width=1005, top=200, left=200, toolbar=no, menubar=no, scrollbars=no, location=no, status=no\')" class="btn btn-xs btn-warning btn-replay">回放</a>'
                            ]).draw();
                        }
                    }
                },
                error: function (response) {
                    $.alert({
                        title: 'Tips',
                        type: 'red',
                        content: response.responseText
                    });
                }
            })
        }
    </script>

    <script>
    $(document).ajaxSend(function(event, xhr, settings) {
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    function sameOrigin(url) {
        // url could be relative or scheme relative or absolute
        var host = document.location.host; // host + port
        var protocol = document.location.protocol;
        var sr_origin = '//' + host;
        var origin = protocol + sr_origin;
        // Allow absolute or scheme relative URLs to same origin
        return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
            (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
            // or any other URL that isn't scheme relative or absolute i.e relative.
            !(/^(\/\/|http:|https:).*/.test(url));
    }
    function safeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    if (!safeMethod(settings.type) && sameOrigin(settings.url)) {
        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    }
});

    </script>
{% endblock %}

apps/webssh/templates/ssh_record_play.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ record.admin_server }}</title>
    <link rel="stylesheet" href="{% static 'plugins/asciinema-player/asciinema-player.css' %}">
</head>
<body>
<div>
    <asciinema-player cols="150" rows="30" src="{{ MEDIA_URL }}{{ record.record_file }}"></asciinema-player>
</div>
<script src="{% static 'plugins/asciinema-player/asciinema-player.js' %}"></script>

</body>
</html>