IDOWN/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'api/', include('api.urls',namespace='api')),
    path('',views.dashboard,name='dashboard'),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('assets/',include('assets.urls',namespace="assets")),
    path('webssh/',include('webssh.urls',namespace='webssh')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 全局403
handler403 = 'IDOWN.views.page_forbidden'

# 全局404
handler404 = 'IDOWN.views.page_not_found'

# 全局500
handler500 = 'IDOWN.views.page_error'

apps/accounts/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2019-07-29 17:07
# @Author  : kbsonlong
# @Email   : kbsonlong@gmail.com
# @Blog    : www.alongparty.cn
# @File    : urls.py
# @Software: PyCharm


from django.urls import path,re_path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/',views.user_login,name = 'login'),
    path('logout/',views.user_logout,name = 'logout'),
    path('user_list/',views.UserListView.as_view(),name = 'user_list'),
    path('group_list/',views.GroupListView.as_view(),name = 'group_list'),
    path('create_user/',views.UserListView.as_view(),name = 'create_user'),
    path('userprofile/<int:pk>/',views.UserDetailView.as_view(),name = 'userprofile'),
    path('reset_password/<int:pk>/',views.reset_password,name = 'reset_password'),

    path(r'create_plan/', views.create_plan, name='create_plan'),
    re_path(r'plan_info/(?P<pk>[0-9]+)/', views.plan_info, name='plan_info'),
]

apps/assets/urls.py
from django.urls import path,include,re_path
from . import views

app_name = 'assets'

urlpatterns = [
    path('assets/',views.AssetListView.as_view(),name='assets_list'),
    path('asset_detail/<int:pk>',views.AssetDetailView.as_view(),name='asset_detail'),
    re_path(r'export_assets/', views.export_assets, name='export_assets'),
]

templates/base/editors.html
{% extends "base/base.html" %}
{% block addcss %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="/static/plugins/editor.md/css/editormd.min.css">
{% endblock %}
{% block content%}
    <section class="content">
        <div class="row">
  <div class="col-md-12">

      <form class="editormd-form col-md-12" action="." method="post" >
          {% csrf_token %}
          <div class="col-md-4">
              <label>配置名称</label>
              <input type="text" class="form-control" name="name" id="name" value="{{ conf.name }}"><small style="color: red">{{ error }}</small>
          </div>
          <div class="col-md-4">
              <label>应用名称</label>
              <select class="form-control selectpicker" name="appname" id="apps"   data-live-search="true" >

              </select>
          </div>
          <div class="col-md-4">
              <div class="btn-group bootstrap-select">
                  <label for="env" class="text-center">所属环境</label>
                      <select class="form-control selectpicker" name="env" id="env"   data-live-search="true" >

                      </select>

              </div>
          </div>
          <hr>
          <div id="editormd">
              <textarea name="context">{{ conf.context }}</textarea>
          </div>

          <input type="submit" class="editormd-btn" value="提交">
      </form>

  </div>
</div>
        <!-- ./row -->
    </section>
{% endblock %}
<!-- ./wrapper -->


{% block addjs %}
    <!-- Select2 -->
{#    <script src="/static/AdminLTE/bower_components/select2/dist/js/select2.full.min.js"></script>#}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
    <!-- (Optional) Latest compiled and minified JavaScript translation files -->
    <script src="https://cdn.bootcss.com/bootstrap-select/2.0.0-beta1/js/i18n/defaults-zh_CN.js"></script>

    <script src="/static/plugins/editor.md/js/editormd.min.js"></script>

    <script>
        $(document).ready(function () {
            var mySelect = $('#first-disabled2');
            $('#special').on('click', function () {
                mySelect.find('option:selected').prop('disabled', true);
                mySelect.selectpicker('refresh');
            });

            $('#special2').on('click', function () {
                mySelect.find('option:disabled').prop('disabled', false);
                mySelect.selectpicker('refresh');
            });

            $('#basic2').selectpicker({
                liveSearch: true,
                maxOptions: 1
            });
        });
    </script>

    <script>
        $('#page_header').text('新增配置');
        $('#page_header_descript').text('New Config');

        $(function () {
            var testEditor = editormd("editormd", {
                width: "100%",
                height: 350,
                syncScrolling: "single",
                path: "/static/plugins/editor.md/lib/",
                imageUpload: true,
                imageFormats: ["jpg", "jpeg", "gif", "png", "bmp"],
                imageUploadURL: "#"
            });
        });

        //获取列表
        function get_list (info){
            $.ajax({
                url: '/api/' + info  + '/',
                type: 'GET',
                success: function (res) {
                    let cabinet_obj = $('#'+info);
                    let cabinets = res;
                    console.log(res);
                    cabinet_obj.html('');
                    for (let i = 0; i < cabinets.length; i++) {
                        cabinet_obj.append(
                            '<option value=' + cabinets[i]['id'] + '>' + cabinets[i]['name_cn'] + '</option>'
                        )
                    }
                }
            })
        }

        $(document).ready(function(){
            get_list('apps');
            get_list('env');
        });

    </script>

{% endblock %}

templates/base/footer.html
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.13
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
    reserved.
  </footer>

templates/base/header.html
<header class="main-header">
    <!-- Logo -->
    <a href="/" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>运维</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>运维管理平台</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <img src="{{ MEDIA_URL }}{{ request.user.image }}" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <!-- end message -->
                  <li>
                    <a href="#">
                      <div class="pull-left">
                        <img src="/static/AdminLTE/dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        AdminLTE Design Team
                        <small><i class="fa fa-clock-o"></i> 2 hours</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <div class="pull-left">
                        <img src="/static/AdminLTE/dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Developers
                        <small><i class="fa fa-clock-o"></i> Today</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <div class="pull-left">
                        <img src="/static/AdminLTE/dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Sales Department
                        <small><i class="fa fa-clock-o"></i> Yesterday</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <div class="pull-left">
                        <img src="/static/AdminLTE/dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Reviewers
                        <small><i class="fa fa-clock-o"></i> 2 days</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- Notifications: style can be found in dropdown.less -->
          <li class="dropdown tasks-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-flag-o"></i>
                            <span class="label label-danger">{{ user.self_user.count }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">
                                你有 {{ request.user.self_user.count }}
                                个任务计划未完成
                            </li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    {% for foo in user.self_user.all %}
                                        <li><!-- Task item -->
                                            <a href="javascript:void(0)">
                                                <h3>
                                                    {{ foo.title }}
                                                    <small class="pull-right">
                                                        截止日期：{{ foo.end_time|date:"Y-m-d H:i:s" }}</small>
                                                </h3>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li class="footer">
                                <a href="{% url 'accounts:userprofile' request.user.id %}">查看所有</a>
                            </li>
                        </ul>
                    </li>
          <!-- Tasks: style can be found in dropdown.less -->
          <li class="dropdown tasks-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li><!-- Task item -->
                    <a href="#">
                      <h3>
                        Design some buttons
                        <small class="pull-right">20%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                  <li><!-- Task item -->
                    <a href="#">
                      <h3>
                        Create a nice theme
                        <small class="pull-right">40%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">40% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                  <li><!-- Task item -->
                    <a href="#">
                      <h3>
                        Some task I need to do
                        <small class="pull-right">60%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">60% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                  <li><!-- Task item -->
                    <a href="#">
                      <h3>
                        Make beautiful transitions
                        <small class="pull-right">80%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">80% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer">
                <a href="#">View all tasks</a>
              </li>
            </ul>
          </li>
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{ MEDIA_URL }}{{ request.user.image }}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ request.user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{{ MEDIA_URL }}{{ request.user.image }}" class="img-circle" alt="User Image">

                <p>
                  {{ request.user.username }} - {% if  request.user.is_superuser  %} 超级管理员{% endif %}
                  <small>{{ request.user.last_login }}</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{% url "accounts:userprofile" request.user.id %}" class="btn btn-default btn-flat">个人中心</a>
                </div>
                <div class="pull-right">
                  <a href="{% url "accounts:logout" %}" class="btn btn-default btn-flat">退出</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

templates/base/sidebar.html
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ MEDIA_URL }}{{ request.user.image }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ request.user.username }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">主菜单</li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/"><i class="fa fa-circle-o"></i> Dashboard</a></li>
                </ul>
            </li>
            {% if request.user.is_superuser %}
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-fw fa-users"></i>
                        <span>用户管理</span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url "accounts:user_list" %}"><i class="fa fa-fw fa-user"></i>用户管理</a></li>
                        <li><a href="{% url "accounts:group_list" %}"><i class="fa fa-fw fa-group"></i> 用户组管理</a></li>
                    </ul>
                </li>
            {% endif %}

            <li class="treeview">
                <a >
                    <i class="fa fa-fw fa-list-ul"></i>
                    <span>资产管理</span>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a>
                            <i class="fa fa-fw fa-dashboard">资产预览</i>
                        </a>
                    </li>
                    <li>
                        <a href="{% url "assets:assets_list" %}">
                            <i class="fa fa-fw fa-server">资产列表</i>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="treeview">
                <a >
                    <i class="fa fa-fw fa-list-ul"></i>
                    <span>项目管理</span>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a>
                            <i class="fa fa-fw fa-dashboard">项目列表</i>
                        </a>
                    </li>
                    <li class="treeview">
                        <a>
                            <i class="fa fa-fw fa-server">项目配置</i>
                        </a>
                        <ul class="treeview-menu">
                            <li class="treeview">
                                <a>配置列表</a>
                            </li>
                            <li class="treeview">
                                <a>项目部署</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>