IDOWN/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'api/', include('api.urls',namespace='api')),
    path('',views.dashboard,name='dashboard'),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('assets/',include('assets.urls',namespace="assets")),
    path('webssh/',include('webssh.urls',namespace='webssh')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 全局403
handler403 = 'IDOWN.views.page_forbidden'

# 全局404
handler404 = 'IDOWN.views.page_not_found'

# 全局500
handler500 = 'IDOWN.views.page_error'

apps/accounts/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2019-07-29 17:07
# @Author  : kbsonlong
# @Email   : kbsonlong@gmail.com
# @Blog    : www.alongparty.cn
# @File    : urls.py
# @Software: PyCharm


from django.urls import path,re_path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/',views.user_login,name = 'login'),
    path('logout/',views.user_logout,name = 'logout'),
    path('user_list/',views.UserListView.as_view(),name = 'user_list'),
    path('group_list/',views.GroupListView.as_view(),name = 'group_list'),
    path('create_user/',views.UserListView.as_view(),name = 'create_user'),
    path('userprofile/<int:pk>/',views.UserDetailView.as_view(),name = 'userprofile'),
    path('reset_password/<int:pk>/',views.reset_password,name = 'reset_password'),

    path(r'create_plan/', views.create_plan, name='create_plan'),
    re_path(r'plan_info/(?P<pk>[0-9]+)/', views.plan_info, name='plan_info'),
]

apps/accounts/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import AbstractUser
# Create your models here.

class UserProfile(AbstractUser):
    login_status_ = (
        (0,'在线'),
        (1,'离线'),
        (2,'忙碌'),
        (3,'离开'),
    )
    mobile = models.CharField(max_length=11,null=True,blank=True,verbose_name="手机号码")
    image = models.ImageField(upload_to='images/%Y/%m/%d/',default='images/default.png',max_length=100)
    login_status = models.SmallIntegerField(choices=login_status_,default=1,verbose_name="登录状态")
    bio = models.TextField(blank=True, null=True)
    # business_unit = models.ForeignKey('assets.BusinessUnit', null=True, blank=True, verbose_name='所属业务线',
    #                                   on_delete=models.SET_NULL)

    def __str__(self):
        return self.username

    class Meta:
        db_table = "ops_user"
        verbose_name = "用户表"
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('accounts:userprofile', args=[self.pk])


class UserLog(models.Model):
    user = models.ForeignKey('UserProfile',on_delete=models.CASCADE,verbose_name="操作用户")
    remote_ip = models.GenericIPAddressField(verbose_name="操作用户IP地址")
    content = models.CharField(max_length=100,verbose_name="操作内容")
    c_time = models.DateTimeField(auto_created=True,verbose_name="操作时间")

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = "ops_user_log"
        verbose_name = "用户操作记录表"
        verbose_name_plural = verbose_name



class UserPlan(models.Model):
    plan_status = (
        (0, '未完成'),
        (1, '已完成')
    )
    user = models.ForeignKey('UserProfile', related_name='self_user', on_delete=models.CASCADE, verbose_name='创建者')
    attention = models.ManyToManyField('UserProfile', related_name='attention_user', blank=True, verbose_name='关注者')
    title = models.CharField(max_length=32, verbose_name='计划标题')
    content = models.TextField(verbose_name='计划内容')
    status = models.PositiveSmallIntegerField(choices=plan_status, verbose_name='任务状态', default=0)
    start_time = models.DateTimeField(default='', verbose_name='开始时间')
    end_time = models.DateTimeField(default='', verbose_name='结束时间')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")

    class Meta:
        db_table = 'ops_users_plan'
        verbose_name = '日程管理'
        verbose_name_plural = verbose_name
        unique_together = ('title', 'user')

apps/accounts/forms.py
# -*- coding: utf-8 -*-
# @Time    : 2019-07-29 16:44
# @Author  : kbsonlong
# @Email   : kbsonlong@gmail.com
# @Blog    : www.alongparty.cn
# @File    : forms.py
# @Software: PyCharm

from django import forms
from .models import UserProfile

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

apps/accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.views.generic import ListView,DetailView
from django.views.generic.edit import UpdateView
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required,permission_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import Group
# Create your views here.

from accounts import models
from accounts.forms import UserLoginForm


def user_login(request):
    """
    用户登录
    :param request:
    :return:
    """
    next_url = request.GET.get('next')
    context = {'next': next_url}
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        remember_me = request.POST.get('remember_me')
        if user_login_form.is_valid():
            ##.cleaned_data清洗出合法数据
            data = user_login_form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user and user.is_active:
                # 将用户数据保存在session中
                login(request, user)
                request.session['username'] = data['username']
                if remember_me:
                    ##选择记住，session过期时间为7天
                    request.session.set_expiry(60 * 60 * 24 * 7)
                    # request.session.set_expiry(60)
                else:
                    ##session默认一小时过期
                    request.session.set_expiry(60 * 60)
                print(request.POST)
                next_url = request.POST.get('next')
                if next_url:
                    return HttpResponseRedirect(request.POST.get('next'))
                else:
                    return redirect("/")
            else:
                context.update({"error": "账号或密码输入错误，请重新输入"})
        else:
            context.update({"error": "账号或密码输入不合法，请重新输入"})
    elif request.method == 'GET':
        if request.session.get('username') and request.session.get('lock'):
            del request.session['lock']
            del request.session['username']
        user_login_form = UserLoginForm()
        context.update({'form': user_login_form})
    else:
        context.update({"error": "请使用GET或者POST请求"})
    return render(request, 'accounts/login1.html', context)

def user_logout(request):
    models.UserProfile.objects.filter(username=request.user).update(
        login_status=1
    )
    logout(request)
    return HttpResponseRedirect('/accounts/login/')



@method_decorator(login_required,name="dispatch")
class UserListView(ListView):
    """
    用户列表
    """
    model = models.UserProfile
    template_name = "accounts/user_list.html"
    context_object_name = "user_list"


@permission_required('accounts.change_userprofile', raise_exception=True)
def reset_password(request, pk):
    """
    重置密码
    :param request:
    :param pk:
    :return:
    """
    if request.method == 'POST':
        try:
            models.UserProfile.objects.filter(id=pk).update(
                password=make_password('123456')
            )

            return JsonResponse({"code": 200, "data": None, "msg": "密码重置成功！密码为123456"})
        except Exception as e:
            return JsonResponse({"code": 500, "data": None, "msg": "密码重置失败，原因：{}".format(e)})


@method_decorator(login_required,name="dispatch")
class GroupListView(ListView):
    """
    用户组列表
    """
    model = Group
    template_name = "accounts/group_list.html"
    context_object_name = "group_list"


@method_decorator(login_required,name="dispatch")
class UserDetailView(DetailView):
    model = models.UserProfile
    template_name = "accounts/user_profile.html"
    context_object_name = "user"
    pk_url_kwarg = "pk"


    def get_context_data(self, **kwargs):
        context = super(UserDetailView,self).get_context_data(**kwargs)
        user = models.UserProfile.objects.get(username=self.request.user)
        # my_plans = user.self_user.filter(status=0) | user.attention_user.filter(status=0)
        my_plans = user.self_user.all() | user.attention_user.all()
        context.update({'my_plans':my_plans})
        return context


def create_plan(request):
    if request.method == 'POST':
        try:
            user_plan = models.UserPlan.objects.create(
                user=models.UserProfile.objects.get(id=request.POST.get('user')),
                title=request.POST.get('title'),
                content=request.POST.get('content'),
                start_time=request.POST.get('start_time'),
                end_time=request.POST.get('end_time'),
            )
            attention = request.POST.getlist('attention')
            if attention:
                user_plan.attention.set(attention)
            return JsonResponse({'code': 200, 'result': True, 'msg': '数据保存成功！'})
        except Exception as e:
            return JsonResponse({'code': 500, 'result': False, 'msg': '数据保存失败！{}'.format(e)})
    users = models.UserProfile.objects.exclude(id__in=[request.user.id])
    return render(request, 'accounts/create_plan.html', locals())


def plan_info(request, pk):
    user_plan = models.UserPlan.objects.prefetch_related('attention').get(id=pk)
    if request.method == 'GET':
        users = models.UserProfile.objects.exclude(id__in=[request.user.id])
        return render(request, 'accounts/plan_info.html', locals())
    elif request.method == 'POST':
        try:
            user_plan.status = 1 if request.POST.get('status') else 0
            user_plan.title = request.POST.get('title')
            user_plan.content = request.POST.get('content')
            user_plan.start_time = request.POST.get('start_time')
            user_plan.end_time = request.POST.get('end_time')
            attention = request.POST.getlist('attention')
            if attention:
                user_plan.attention.set(attention)
            else:
                user_plan.attention.clear()
            user_plan.save()
            return JsonResponse({'code': 200, 'result': True, 'msg': '数据保存成功！'})
        except Exception as e:
            return JsonResponse({'code': 500, 'result': False, 'msg': '数据保存失败！{}'.format(e)})
    elif request.method == 'DELETE':
        try:
            user_plan.delete()
            return JsonResponse({'code': 200, 'result': True, 'msg': '数据删除成功！'})
        except Exception as e:
            return JsonResponse({'code': 500, 'result': False, 'msg': '数据删除失败！{}'.format(e)})

apps/accounts/templates/accounts/base-layer.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'AdminLTE/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/layer/skin/layer.css' %}">
    <link rel="stylesheet" href="{% static 'AdminLTE/bower_components/select2/dist/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'AdminLTE/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'AdminLTE/plugins/iCheck/all.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/jquery-confirm/dist/jquery-confirm.min.css' %}">
    {% block header %}

    {% endblock %}
</head>

<body>
{% block main %}
{% endblock %}

<script src="{% static 'AdminLTE/bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'plugins/layer/layer.js' %}"></script>
<script src="{% static 'AdminLTE/bower_components/select2/dist/js/select2.full.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/iCheck/icheck.min.js' %}"></script>

<script type="text/javascript">
    $(function () {
        $(".form_datetime").datetimepicker({
            language: 'zh',
            //minView: 'month',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 0,
            //format: 'yyyy-mm-dd hh:ss'
        }).on('changeDate', function (ev) {
            $(this).datetimepicker('hide');
        });

        $(".select2").select2();

        $('input[type="checkbox"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
        })
    })
</script>

{% block javascripts %}

{% endblock %}

</body>
</html>

apps/accounts/templates/accounts/create_plan.html
{% extends 'accounts/base-layer.html' %}

{% block main %}
    <div class="box box-danger">
        <form class="form-horizontal" id="addForm" method="post">
            {% csrf_token %}
            <input type="hidden" name='user' value="{{ request.user.id }}"/>
            <div class="box-body">
                <fieldset>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label" for="start_time">开始时间</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control pull-right form_datetime" name="start_time"
                                   id="start_time" readonly>
                        </div>
                        <label class="col-sm-2 control-label" for="end_time">结束时间</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control pull-right form_datetime" name="end_time"
                                   id="end_time" readonly/>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label" for="title">任务标题</label>
                        <div class="col-sm-3" style="width: 48%">
                            <input type="text" class="form-control pull-right" name="title" id="title" required>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label" for="content">计划内容</label>
                        <div class="col-sm-8">
                            <textarea class="form-control" name="content" id="content" rows="5"></textarea>
                        </div>
                    </div>

                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label" for="multiple">添加关注</label>
                        <div class="col-sm-3" style="width: 48%">
                            <select class="form-control select2" multiple="multiple" name="attention" id="multiple"
                                    data-placeholder="添加关注"
                                    style="width: 100%;">
                                {% for attention in users %}
                                    <option value="{{ attention.id }}">{{ attention.username }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <span><small class="text-danger margin-l-5">* 关注人可以查看本条内容</small></span>
                    </div>
                </fieldset>
            </div>
            <div class="box-footer ">

                <div class="row span7 text-center ">
                    <button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
                    <button type="button" id="btnSave" class="btn btn-info margin-right ">保存</button>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $("#btnSave").click(function () {
            let data = $("#addForm").serialize();
            $.ajax({
                type: 'POST',
                url: "{% url 'accounts:create_plan' %}",
                data: data,
                traditional: true,
                dataType: 'json',
                cache: false,
                success: function (res) {
                    if (res.result) {
                        layer.alert(res.msg, {icon: 1}, function () {
                            parent.location.reload();
                        });
                    } else {
                        layer.alert(res.msg, {icon: 5});
                        //$('errorMessage').html(msg.message)
                    }
                }
            });
        });


        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();

        });
    </script>

{% endblock %}

apps/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="/static/AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	
	<!-- Font Awesome -->
	<link href="/static/AdminLTE/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	
	<!-- Endless -->
{#	<link href="/static/AdminLTE/dist/css/endless.min.css" rel="stylesheet">#}

  </head>

  <body>
	<div class="login-wrapper">
		<div class="text-center">
			<h2 class="fadeInUp animation-delay8" style="font-weight:bold">
				<span class="text-success">运维管理平台</span>
			</h2>
		</div>
		<div class="login-widget animation-delay1">	
			<div class="panel panel-default">
				<div class="panel-heading clearfix">
					<div class="pull-left">
						<i class="fa fa-lock fa-lg"></i> 登入
					</div>
                    <small style="color: red">{{ error }}</small>
					<div class="pull-right">
						<span style="font-size:11px;">没有账号？请找运维组申请账号</span>
{#						<a class="btn btn-default btn-xs login-link" href="register.html" style="margin-top:-2px;"><i class="fa fa-plus-circle"></i>注册</a>#}
					</div>
				</div>
				<div class="panel-body">
					<form class="form-login" method="post" action="{% url 'accounts:login' %}">
                        {% csrf_token %}
						<div class="form-group">
							<label>用户</label>
                            <input type="hidden" name="next" value="{{ next }}" />
							<input type="text" name="username" placeholder="Username" class="form-control input-sm bounceIn animation-delay2" >
						</div>
						<div class="form-group">
							<label>密码</label>
							<input type="password" name="password" placeholder="Password" class="form-control input-sm bounceIn animation-delay4">
						</div>
						<div class="form-group">
							<label class="label-checkbox inline">
                                <input type="checkbox" name="remember_me" class="regular-checkbox chk-delete" />
								<span class="custom-checkbox info bounceIn animation-delay4"></span>
							</label>
							记住我！
						</div>
		
						<div class="seperator"></div>
						<div class="form-group">
							忘记密码？<br/>
{#							点击 <a href="#">找回</a> 密码#}
                            请联系运维组重置密码
						</div>

						<hr/>
                        {% if form.errors %}
                        <span style="color:#F00">用户名或密码错误！ </span>
{#                            <input type="hidden" name="next" value={{ next }}>#}
                        {% else %}
                            <input type="hidden" name="next" value="/">
{#                            <span style="color:#0000ff">支持LDAP登录了哦！</span>#}
                        {% endif %}
{#                    {{ form.non_field_errors }}#}
						<button class="btn btn-success btn-sm bounceIn animation-delay5 pull-right" type="submit"><i class="fa fa-sign-in"></i> 登入</button>
					</form>
				</div>
			</div><!-- /panel -->
		</div><!-- /login-widget -->
	</div><!-- /login-wrapper -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <!-- Jquery -->
	<script src="/static/AdminLTE/bower_components/jquery/dist/jquery.min.js"></script>
    
    <!-- Bootstrap -->
    <script src="/static/AdminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

  </body>
</html>

apps/accounts/templates/accounts/plan_info.html
{% extends 'accounts/base-layer.html' %}
{% load staticfiles %}

{% block main %}
    <div class="box box-danger">
        <div class="box-header with-border">
            <div class="user-block">
                <img class="img-circle" src="{{ MEDIA_URL }}{{ user.image }}" alt="User Image">
                <span class="username"><a href="javascript:void(0)">{{ user_plan.user.username }}</a></span>
                <span class="description">创建时间: {{ user_plan.add_time|date:'Y-m-d H:i:s' }}</span>
            </div>
            <!-- /.user-block -->
            <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-toggle="tooltip" title="Mark as read">
                    <i class="fa fa-circle-o"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
            <!-- /.box-tools -->
        </div>

        <form class="form-horizontal" id="addForm" method="post">
            {% csrf_token %}
            <div class="box-body">
                <fieldset>
                    <input type="hidden" name='user' value="{{ request.user.id }}">
                    <input type="hidden" name="pk" value="{{ user_plan.id }}" id="plan-id">
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label" for="start_time">开始时间</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control pull-right form_datetime" name="start_time"
                                   id="start_time" value="{{ user_plan.start_time |date:'Y-m-d H:i' }}" readonly>
                        </div>
                        <label class="col-sm-2 control-label" for="end_time">结束时间</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control pull-right form_datetime" name="end_time"
                                   id="end_time" value="{{ user_plan.end_time |date:'Y-m-d H:i' }}" readonly/>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label" for="title">任务标题</label>
                        <div class="col-sm-3" style="width: 48%">
                            <input type="text" class="form-control pull-right" name="title" id="title"
                                   value="{{ user_plan.title }}" required>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label" for="content">计划内容</label>
                        <div class="col-sm-8">
                            <textarea class="form-control" name="content" id="content"
                                      rows="5">{{ user_plan.content }}</textarea>
                        </div>
                    </div>

                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label" for="multiple">添加关注</label>
                        <div class="col-sm-3" style="width: 48%">
                            <select class="form-control select2" multiple="multiple" name="attention" id="multiple"
                                    data-placeholder="添加关注" style="width: 100%;">
                                {% for attention in users %}
                                    {% if attention in user_plan.attention.all %}
                                        <option value="{{ attention.id }}" selected>{{ attention.username }}</option>
                                    {% else %}
                                        <option value="{{ attention.id }}">{{ attention.username }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <span><small class="text-danger margin-l-5">* 关注人可以查看本条内容</small></span>
                    </div>

                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label" for="status">是否完成</label>
                        <div class="col-sm-3" style="padding-top: 7px; margin-bottom: 0">
                            <input type="checkbox" class="form-control pull-right minimal" name="status" id="status">
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="box-footer ">

                <div class="row span7 text-center ">
                    {% ifequal request.user.id  user_plan.user_id %}
                        <button type="button" id="btnSave" class="btn btn-info margin-right ">保存修改</button>
                        <button type="button" id="btnDelete" class="btn btn-warning margin-right ">删除</button>
                    {% endifequal %}
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/jquery-confirm/dist/jquery-confirm.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            {% if user_plan.status == 1 %}
                $('#status').iCheck('check');
            {% endif %}
        });
        $("#btnSave").click(function () {
            let data = $("#addForm").serialize();

            $.ajax({
                type: 'POST',
                url: "{% url 'accounts:plan_info' pk %}",
                data: data,
                traditional: true,
                dataType: 'json',
                success: function (res) {
                    if (res.result) {
                        layer.alert(res.msg, {icon: 1}, function () {
                            parent.location.reload();
                        });
                    } else {
                        layer.alert(res.msg, {icon: 5});
                        //$('errorMessage').html(msg.message)
                    }
                }
            });

        });

        $('#btnDelete').on('click', function () {
            $.confirm({
                title: 'Tips',
                content: '确定要删除该任务么？',
                type: 'red',
                buttons: {
                    Ok: function () {
                        $.ajax({
                            type: "{% url 'accounts:plan_info' pk %}",
                            method: 'DELETE',
                            beforeSend: function (xhr, settings) {
                                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");

                            },
                            success: function (res) {
                                if (res.result) {
                                    layer.alert(res.msg, {icon: 1}, function () {
                                        parent.location.reload();
                                    });
                                } else {
                                    layer.alert(res.msg, {icon: 5});
                                    //$('errorMessage').html(msg.message)
                                }
                            }
                        })
                    },
                    Cancel: function () {
                        //
                    }
                }
            });
        });


        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();

        });
    </script>

{% endblock %}