IDOWN/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'api/', include('api.urls',namespace='api')),
    path('',views.dashboard,name='dashboard'),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('assets/',include('assets.urls',namespace="assets")),
    path('webssh/',include('webssh.urls',namespace='webssh')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 全局403
handler403 = 'IDOWN.views.page_forbidden'

# 全局404
handler404 = 'IDOWN.views.page_not_found'

# 全局500
handler500 = 'IDOWN.views.page_error'

apps/assets/urls.py
from django.urls import path,include,re_path
from . import views

app_name = 'assets'

urlpatterns = [
    path('assets/',views.AssetListView.as_view(),name='assets_list'),
    path('asset_detail/<int:pk>',views.AssetDetailView.as_view(),name='asset_detail'),
    re_path(r'export_assets/', views.export_assets, name='export_assets'),
]

apps/assets/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.


User = get_user_model()

class Asset(models.Model):
    """所有资产的共有数据表"""

    asset_type_choice = (
        ('server', '服务器'),
        ('networkdevice', '网络设备'),
        ('storagedevice', '存储设备'),
        ('securitydevice', '安全设备'),
        ('software', '软件资产'),
    )

    asset_status = (
        (0, '在线'),
        (1, '下线'),
        (2, '未知'),
        (3, '故障'),
        (4, '备用'),
        (5, '待初始化'),
    )

    type = models.CharField(choices=asset_type_choice, max_length=64, default='server', verbose_name='资产类型')
    name = models.CharField(max_length=64, unique=True, verbose_name='资产名称')  # 不可重复
    sn = models.CharField(max_length=128, unique=True, verbose_name='资产序列号')
    business_unit = models.ForeignKey('BusinessUnit', null=True, blank=True, verbose_name='所属业务线',
                                      on_delete=models.SET_NULL)

    status = models.SmallIntegerField(choices=asset_status, default=0, verbose_name='设备状态')

    manufacturer = models.ForeignKey('Manufacturer', null=True, blank=True, verbose_name='IDC服务商',
                                     on_delete=models.SET_NULL)
    manage_ip = models.GenericIPAddressField(null=True, blank=True, verbose_name='管理IP')
    admin = models.ForeignKey(User, null=True, blank=True, verbose_name='资产管理员', related_name='admin',
                              on_delete=models.SET_NULL)
    idc = models.ForeignKey('IDC', null=True, blank=True, verbose_name='所在机房', on_delete=models.SET_NULL)

    purchase_day = models.DateField(null=True, blank=True, verbose_name="购买日期")
    expire_day = models.DateField(null=True, blank=True, verbose_name="过保日期")
    price = models.FloatField(null=True, blank=True, verbose_name="价格")

    approved_by = models.ForeignKey(User, null=True, blank=True, verbose_name='批准人', related_name='approved_by',
                                    on_delete=models.SET_NULL)

    remark = models.TextField(null=True, blank=True, verbose_name='备注')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='批准日期')
    m_time = models.DateTimeField(auto_now=True, verbose_name='更新日期')

    def __str__(self):
        return '<%s>  %s' % (self.get_type_display(), self.name)

    class Meta:
        verbose_name = '资产总表'
        verbose_name_plural = "资产总表"
        ordering = ['-c_time']


class Server(models.Model):
    """服务器设备"""

    sub_asset_type_choice = (
        (0, 'ECS'),
        (1, 'PC服务器'),
        (2, '小型机'),
    )

    created_by_choice = (
        ('auto', '自动添加'),
        ('manual', '手工录入'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)  # 非常关键的一对一关联！asset被删除的时候一并删除server
    i_ip = models.GenericIPAddressField(verbose_name="公网地址",  blank=True, null=True, default=None)
    local_ip = models.GenericIPAddressField(verbose_name="内网地址", blank=True, null=True, default=None)
    instance_id = models.CharField(verbose_name="ECS实例ID",max_length=100, blank=True, null=True, default=None)
    hostname = models.CharField(verbose_name="服务器主机名",max_length=150, blank=True, null=True, default=None)
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="服务器类型")
    created_by = models.CharField(choices=created_by_choice, max_length=32, default='auto', verbose_name="添加方式")
    hosted_on = models.ForeignKey('self', related_name='hosted_on_server',
                                  blank=True, null=True, verbose_name="宿主机", on_delete=models.CASCADE)  # 虚拟机专用字段
    model = models.CharField(max_length=128, null=True, blank=True, verbose_name='服务器型号')
    raid_type = models.CharField(max_length=512, blank=True, null=True, verbose_name='Raid类型')
    env = models.ForeignKey('Env', max_length=64, blank=True, null=True,on_delete=models.SET_NULL,verbose_name="所属环境")
    os_distribution = models.CharField('发行商', max_length=64, blank=True, null=True)
    os_release = models.CharField('操作系统版本', max_length=512, blank=True, null=True)
    cpu = models.CharField('CPU', max_length=64, blank=True, null=True)
    ram = models.CharField('内存', max_length=64, blank=True, null=True)

    def __str__(self):
        return '%s--%s--%s' % (self.hostname, self.get_sub_asset_type_display(), self.i_ip)

    class Meta:
        verbose_name = '服务器'
        verbose_name_plural = "服务器"


class Env(models.Model):
    name = models.CharField(verbose_name='环境名称',max_length=20,unique=True,help_text='dev',null=True,blank=True)
    name_cn = models.CharField(verbose_name='环境中文名称',max_length=20,help_text='开发环境',null=True,blank=True)
    class Meta:
        verbose_name = "环境名称"
        verbose_name_plural = "环境名称"
    def __str__(self):
        return self.name


class IDC(models.Model):
    """机房"""
    name = models.CharField(max_length=64, unique=True, verbose_name="机房名称")
    memo = models.CharField(max_length=128, blank=True, null=True, verbose_name='备注')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机房'
        verbose_name_plural = "机房"


class Manufacturer(models.Model):
    """IDC服务商"""

    name = models.CharField('IDC名称', max_length=64, unique=True)
    telephone = models.CharField('支持电话', max_length=30, blank=True, null=True)
    memo = models.CharField('备注', max_length=128, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'IDC服务商'
        verbose_name_plural = "IDC服务商"


class BusinessUnit(models.Model):
    """业务线"""

    parent_unit = models.ForeignKey('self', blank=True, null=True, related_name='parent_level',
                                    on_delete=models.SET_NULL)
    name = models.CharField('业务线', max_length=64, unique=True)
    memo = models.CharField('备注', max_length=64, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '业务线'
        verbose_name_plural = "业务线"


class App(models.Model):
    app_type_choice = (
        (0, 'api'),
        (1, 'base'),
        (2, 'db'),
        (3, 'dubbo'),
        (4, 'messages'),
        (5, 'search'),
        (6, 'web'),
    )
    active_choices = (
        (1, '在线'),
        (4, '禁用'),
        (9, '废弃'),
    )
    server = models.ManyToManyField('Server',verbose_name="部署主机")
    env = models.ForeignKey('Env',verbose_name="所属环境",on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=150,verbose_name="应用名称")
    name_cn = models.CharField(max_length=200,null=True,blank=True,verbose_name="应用中文名称")
    app_type = models.SmallIntegerField(choices=app_type_choice,  default=0, verbose_name='应用类型')
    domain = models.CharField(max_length=100,default='',verbose_name="域名")
    port  = models.IntegerField(default=0,verbose_name="应用端口")
    values  = models.CharField(max_length=500,default="'-Xms512m -Xmx512m'",verbose_name="启动参数")
    war_name  = models.CharField(max_length=200,default="app_name.jar",verbose_name="应用包名称")
    leader  = models.CharField(max_length=200,default="",verbose_name="应用负责人")
    remark = models.TextField(null=True, blank=True, verbose_name='备注')
    active  = models.SmallIntegerField(choices=active_choices,default=1,verbose_name="应用状态")
    app_init = models.CharField(default='n',max_length=10,verbose_name="应用是否初始化")
    create_user = models.CharField(default='',blank=True,null=True,max_length=50,verbose_name="创建人")
    create_time = models.DateField(auto_now_add=True,verbose_name="创建日期")
    update_user = models.CharField(default='',blank=True,null=True,max_length=10,verbose_name="更新人")
    update_time = models.DateTimeField(auto_now=True,verbose_name="更新时间")
    member = models.ManyToManyField(User,verbose_name="项目成员",help_text="一个应用对应多个成员")
    class Meta:
        verbose_name = "应用程序"
        verbose_name_plural = "应用程序"
        unique_together =('name','env')

    def __str__(self):
        return '{}'.format(self.name)



class SecurityDevice(models.Model):
    """安全设备"""

    sub_asset_type_choice = (
        (0, '防火墙'),
        (1, '入侵检测设备'),
        (2, '互联网网关'),
        (4, '运维审计系统'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="安全设备类型")
    model = models.CharField(max_length=128, default='未知型号', verbose_name='安全设备型号')

    def __str__(self):
        return self.asset.name + "--" + self.get_sub_asset_type_display() + str(self.model) + " id:%s" % self.id

    class Meta:
        verbose_name = '安全设备'
        verbose_name_plural = "安全设备"


class StorageDevice(models.Model):
    """存储设备"""

    sub_asset_type_choice = (
        (0, '磁盘阵列'),
        (1, '网络存储器'),
        (2, '磁带库'),
        (4, '磁带机'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="存储设备类型")
    model = models.CharField(max_length=128, default='未知型号', verbose_name='存储设备型号')

    def __str__(self):
        return self.asset.name + "--" + self.get_sub_asset_type_display() + str(self.model) + " id:%s" % self.id

    class Meta:
        verbose_name = '存储设备'
        verbose_name_plural = "存储设备"


class NetworkDevice(models.Model):
    """网络设备"""

    sub_asset_type_choice = (
        (0, '路由器'),
        (1, '交换机'),
        (2, '负载均衡'),
        (4, 'VPN设备'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="网络设备类型")

    vlan_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name="VLanIP")
    intranet_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name="内网IP")

    model = models.CharField(max_length=128, default='未知型号',  verbose_name="网络设备型号")
    firmware = models.CharField(max_length=128, blank=True, null=True, verbose_name="设备固件版本")

apps/api/views/asset_views.py
# -*- coding: utf-8 -*-
# @Time    : 2019-07-30 14:15
# @Author  : kbsonlong
# @Email   : kbsonlong@gmail.com
# @Blog    : www.alongparty.cn
# @File    : asset_views.py
# @Software: PyCharm
from rest_framework import viewsets, permissions

from api.serializers.asset_serializers import *
from assets import models


class AssetsViewSet(viewsets.ModelViewSet):
    """
    资产管理
    """
    queryset = models.Asset.objects.all().order_by('id')
    serializer_class = AssetSerializer
    permission_classes = (permissions.IsAuthenticated,)



class ServerViewSet(viewsets.ModelViewSet):
    """
    服务器列表
    """
    queryset = models.Server.objects.all().order_by('id')
    serializer_class = ServerSerializer
    permission_classes = (permissions.IsAuthenticated,)


class EnvsViewSet(viewsets.ModelViewSet):
    """
    环境列表
    """
    queryset = models.Env.objects.all().order_by('id')
    serializer_class = EnvSerializer
    permission_classes = (permissions.IsAuthenticated,)


class IdcViewSet(viewsets.ModelViewSet):
    """
    机房列表
    """
    queryset = models.IDC.objects.all().order_by('id')
    serializer_class = IdcSerializer
    permission_classes = (permissions.IsAuthenticated,)

class BusinessUnitViewSet(viewsets.ModelViewSet):
    """
    业务线管理
    """
    queryset = models.BusinessUnit.objects.all().order_by('id')
    serializer_class = BusinessUnitSerializer
    permission_classes = (permissions.IsAuthenticated,)


class AppViewSet(viewsets.ModelViewSet):
    """
    应用管理
    """
    queryset = models.App.objects.all().order_by('id')
    serializer_class = AppSerializer
    permission_classes = (permissions.IsAuthenticated,)

apps/assets/views.py
import json
import xlwt
import logging
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required
from django.http import FileResponse
# Create your views here.
from . import models
from .utils.tools import ExportExcel

@method_decorator(login_required,name="dispatch")
class AssetListView(ListView):
    model = models.Asset
    template_name = "assets/assets_list.html"
    context_object_name = 'assets_list'


    def get_context_data(self, *args, **kwargs):
        context = super(AssetListView,self).get_context_data(*args, **kwargs)
        asset_types = models.Asset.asset_type_choice
        asset_status = models.Asset.asset_status
        server_types = models.Server.sub_asset_type_choice
        context.update({'asset_types':asset_types,'server_types':server_types,'asset_status_':asset_status})
        return context


@method_decorator(login_required,name="dispatch")
class AssetDetailView(DetailView):
    model = models.Asset
    template_name = "assets/asset_detail.html"
    context_object_name = "asset"



@permission_required('assets.add_assets', raise_exception=True)
def export_assets(request):
    if request.method == 'POST':
        pks = request.POST.get('pks')
        server_row = network_row = office_row = security_row = storage_row = software_row = 1
        excel = None
        filename = '资产列表.csv'
        try:
            file = xlwt.Workbook(encoding='utf-8', style_compression=0)

            # 生成sheet
            server_sheet = file.add_sheet('server', cell_overwrite_ok=True)
            network_sheet = file.add_sheet('network', cell_overwrite_ok=True)
            office_sheet = file.add_sheet('office', cell_overwrite_ok=True)
            security_sheet = file.add_sheet('security', cell_overwrite_ok=True)
            storage_sheet = file.add_sheet('storage', cell_overwrite_ok=True)
            software_sheet = file.add_sheet('software', cell_overwrite_ok=True)

            # 导出数据
            for pk in json.loads(pks):
                asset = models.Asset.objects.get(id=int(pk))

                if asset.type == 'server':
                    excel = ExportExcel(filename, excel_obj=file, asset_obj=asset, sheet_name=server_sheet)
                    excel.gen_body(server_row)
                    server_row = server_row + 1
                elif asset.type == 'network':
                    excel = ExportExcel(filename, excel_obj=file, asset_obj=asset, sheet_name=network_sheet)
                    excel.gen_body(network_row)
                    network_row = network_row + 1
                elif asset.type == 'office':
                    excel = ExportExcel(filename, excel_obj=file, asset_obj=asset, sheet_name=office_sheet)
                    excel.gen_body(office_row)
                    office_row = office_row + 1
                elif asset.type == 'security':
                    excel = ExportExcel(filename, excel_obj=file, asset_obj=asset, sheet_name=security_sheet)
                    excel.gen_body(security_row)
                    security_row = security_row + 1
                elif asset.type == 'storage':
                    excel = ExportExcel(filename, excel_obj=file, asset_obj=asset, sheet_name=storage_sheet)
                    excel.gen_body(storage_row)
                    storage_row = storage_row + 1
                elif asset.type == 'software':
                    excel = ExportExcel(filename, excel_obj=file, asset_obj=asset, sheet_name=software_sheet)
                    excel.gen_body(software_row)
                    software_row = software_row + 1
                excel.gen_headers()
            excel.save_excel()
            response = FileResponse(excel.download_excel())
            response['Content-Type'] = 'application/octet-stream'
            response['charset'] = 'utf-8'
            response['Content-Disposition'] = 'attachment;filename="{filename}"'.format(filename=filename)
            return response
        except Exception as e:
            logging.getLogger().error('导出失败！{}'.format(e))

apps/assets/templates/assets/asset_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}资产详细{% endblock %}

{% block css %}

{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        资产详细
        <small>asset info</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li>资产总表</li>
        <li class="active">资产详细</li>
      </ol>
    </section>
{% endblock %}

{% block content %}

     <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">

        <div class="box-header with-border">
            <h3 class="box-title"><strong class="btn btn-block btn-primary btn-lg">资产：{{ asset.server.hostname }}</strong></h3>

            <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
            </div>
        </div>

        <div class="box-body">

            <h4><b>概览:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue" >
                <thead>
                    <tr>
                        <th>类型</th>
                        <th>SN</th>
                        <th>业务线</th>
                        <th>公网地址</th>
                        <th>私网地址</th>
                        <th>机房</th>
                        <th>标签</th>
                        <th>更新日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.get_type_display }}</td>
                    <td>{{ asset.sn }}</td>
                    <td>{{ asset.business_unit|default:'N/A' }}</td>
                    <td>{{ asset.server.i_ip|default:'N/A' }}</td>
                    <td>{{ asset.server.local_ip|default:'N/A' }}</td>
                    <td>{{ asset.idc|default:'N/A' }}</td>
                    <td>
                        {% for tag in asset.tags.all %}
                        <label class="label label-primary">{{ tag.name }}</label>
                        {% empty %}
                            -
                        {% endfor %}
                    </td>
                    <td>{{ asset.m_time }}</td>
                </tr>
                </tbody>
            </table>
            <br />
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue">
                <thead>
                    <tr>
                        <th>价格</th>
                        <th>购买日期</th>
                        <th>过保日期</th>
                        <th>管理员</th>
                        <th>批准人</th>
                        <th>备注</th>
                        <th>批准日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.price|default:'N/A' }}</td>
                    <td>{{ asset.purchase_day|default:'N/A' }}</td>
                    <td>{{ asset.expire_day|default:'N/A' }}</td>
                    <td>{{ asset.admin|default:'N/A' }}</td>
                    <td>{{ asset.approved_by|default:'N/A' }}</td>
                    <td>{{ asset.memo|default:'N/A' }}</td>
                    <td>{{ asset.m_time }}</td>
                </tr>
                </tbody>
            </table>

            <h4><b>服务器:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid green;border-bottom:1px solid green">
                <thead>
                    <tr>
                        <th>服务器类型</th>
                        <th>主机名称</th>
                        <th>阿里云实例ID</th>
                        <th>宿主机</th>
                        <th>所属环境</th>
                        <th>内存(MB)</th>
                        <th>CPU核数</th>
                        <th>OS版本</th>
                        <th>添加方式</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.server.get_sub_asset_type_display }}</td>
                    <td>{{ asset.server.hostname|default:'N/A' }}</td>
                    <td>{{ asset.server.instance_id|default:'N/A' }}</td>
                    <td>{{ asset.server.hosted_on.id|default:'N/A' }}</td>
                    <td>{{ asset.server.env.name }}</td>
                    <td>{{ asset.server.ram|default:'N/A' }}</td>
                    <td>{{ asset.server.cpu|default:'N/A' }}</td>
                    <td>{{ asset.server.os_release|default:'N/A' }}</td>
                    <td>{{ asset.server.get_created_by_display }}</td>
                </tr>
                </tbody>
            </table>
{##}
            <h4><b>应用:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid brown;border-bottom:1px solid brown">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>应用名称</th>
                        <th>应用中文名称</th>
                        <th>应用类型</th>
                        <th>应用状态</th>
                        <th>应用负责人</th>
                        <th>应用上线时间</th>
                    </tr>
                </thead>
                <tbody>
                {% for app in asset.server.app_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'assets:app_detail' app.id %}">{{ app.name|default:'N/A' }}</a></td>
                        <td>{{ app.name_cn|default:'N/A' }}</td>
                        <td>{{ app.get_app_type_display }}</td>
                        {% if app.active == 1 %}
                          <td><label class="label label-success">{{ app.get_active_display}}</label></td>
                        {% elif app.active == 4 %}
                          <td><label class="label label-warning">{{ app.get_active_display}}</label></td>
                        {% elif app.active == 9 %}
                          <td><label class="label label-info">{{ app.get_active_display}}</label></td>
                        {% endif %}
                        <td>{{ app.leader }}</td>
                        <td>{{ app.create_time }}</td>
                    </tr>
                {% empty %}
                    暂无部署应用
                {% endfor %}
                </tbody>
            </table>


        </div>
        <!-- /.box-body -->



        <div class="box-footer">
          <i class="fa fa-angle-double-left"></i>&nbsp;&nbsp;<a href="{% url 'assets:assets_list' %}"><strong>返回资产列表页</strong></a>
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->


{% endblock %}

{% block script %}

{% endblock %}